export const types = {
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',

    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',

    REMOVE_TASK:         'REMOVE_TASK',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',

    UPDATE_TASK:         'UPDATE_TASK',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',

    COMPLETE_ALL_TASKS:         'COMPLETE_ALL_TASKS',
    COMPLETE_ALL_TASKS_SUCCESS: 'COMPLETE_ALL_TASKS_SUCCESS',
};
