export const types = {
    FETCH_TASKS:         'FETCH_TASKS',
    FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAIL:    'FETCH_TASKS_FAIL',

    CREATE_TASK:         'CREATE_TASK',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL:    'CREATE_TASK_FAIL',

    REMOVE_TASK:         'REMOVE_TASK',
    REMOVE_TASK_SUCCESS: 'REMOVE_TASK_SUCCESS',
    REMOVE_TASK_FAIL:    'REMOVE_TASK_FAIL',

    UPDATE_TASK:         'UPDATE_TASK',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAIL:    'UPDATE_TASK_FAIL',

    COMPLETE_ALL_TASKS:         'COMPLETE_ALL_TASKS',
    COMPLETE_ALL_TASKS_SUCCESS: 'COMPLETE_ALL_TASKS_SUCCESS',
    COMPLETE_ALL_TASKS_FAIL:    'COMPLETE_ALL_TASKS_FAIL',
};
